config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'groups#new'
  resources :users, only: [:index, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.text?
        last_message.text
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.text?
        last_message.text
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # user = User.find(params[:user_id])
    # last_message_id = params[:id]
    # @messages = user.messages.includes(:user).where("id > ?", last_message_id)

    group = Group.find(params[:group_id])
    last_message_id = params[:id]
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  before_action :set_user

  def index
    @message = Message.new
    @UserMessage = @user.messages.includes(:user)
    @GroupMessage = @group.messages.includes(:user)
  end

  def create
    @UserMessage = @user.messages.new(message_params)
    if @UserMessage.save
      respond_to do |format|
        format.json
      end
    else
      @UserMessage = @user.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
    
    @GroupMessage = @group.messages.new(message_params)
    if @GroupMessage.save
      respond_to do |format|
        format.json
      end
    else
      @GroupMessage = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with class: "Form", model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__main
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__main
      %label.SettingGroupForm__label チャットメンバーを追加
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
        .result
          #UserSearchResult
  .SettingGroupForm__field
    .SettingGroupForm__show
      = f.label :name, value: "チャットメンバー : ", class: "SettingGroupForm__label"
    .SettingGroupForm__main
      .ChatMembers
        .ChatMember
          %p.member__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if current_user.name != user.name
            .ChatMember
              %p.member__name
                = user.name
              .member__remove.member__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              %input{name: "group[user_ids][]", type:"hidden", value: user.id}
  .SettingGroupForm__field
    .SettingGroupForm__main
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  .SettingGroupForm__title
    %h1 チャットグループ編集
    = link_to "トップページに戻る", :back, class: 'button'
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
-# = render 'messages/header'
-# .wrapper
-#   = render 'messages/side'

app/views/groups/new.html.haml
= form_with model: @group, local: true do |f|
  = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "Save", class: "SettingGroupForm__button"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TakeAChat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = render 'messages/header'
    .wrapper
      = render 'messages/side'
    = yield

app/views/messages/_header.html.haml
.header
  .header__info
    .header__info__user-icon
      = icon('fas', 'user')
    %h3.header__info__user-name
      = current_user.name

  -# .header__search
  -#   %form{class: "search"}
  -#     %input{placeholder: "検索", class: "search__form" }
  -#     %input{type: "submit", value: "検索", class: "search__btn"}

  .header__icons
    = link_to edit_user_path(current_user), class: "header__icons__btn" do
      = icon('fas', 'cog', class: "header-btn")
      アカウント編集
    = link_to destroy_user_session_path, method: :delete, class: "header__icons__btn" do
      =icon('fas', 'sign-out-alt', class: "header-btn")
      ログアウト

app/views/messages/_main.html.haml
.main
  .chat-header
    .chat-header__group
      .chat-header__group__name
        = @group.name
        .group__member
          %span (
          #membership
            = @group.users.length
          %span )
        %ul.memberlists

      .chat-header__group__edit
        = link_to edit_group_path(@group), class: "edit" do
          = icon('fas', 'bars', class: "edit-btn")
          グループ編集

  %ul.chat-log
    = render @messages
  
  .chat-form
    = form_with model: [@group, @message], html: {class: "form"}, local: true do |f|
      = f.label :image, class: "image-file", title: "画像を選択" do
        = icon('far', 'folder-open', class: "image")
        = f.file_field :image, class: "file"
      .form__message
        = f.text_field :text, class: "text"
      = f.submit "送信", class: "send"

app/views/messages/_message.html.haml
%li.chat{data: {message: {id: message.id}}}
  .chat__user 
    = message.user.name
  .chat__comment
    - if message.text.present?
      %p.chat__text
        = message.text
    = image_tag message.image.url, size: "300x300", class: 'chat__image' if message.image.present?
  .chat__day
    .chat__day__time
      = message.created_at.strftime("%H:%M")
-# %li.chat-current
-#   .chat-current__user
-#     = current_user.name
-#   .chat-current__comment
-#     - if message.text.present?
-#       %p.chat__text
-#         = message.text
-#     = image_tag message.image.url, class: 'chat-current__image' if message.image.present?
-#   .chat-current__day
-#     .chat-current__day__time
-#       = message.created_at.strftime("%H:%M")

app/views/messages/_side.html.haml
.side
  .side__group-lists
    グループ
    = link_to new_group_path, class: "member-add" do
      = icon('fas', 'plus-square', class: 'addition')
      -# %span メンバーを追加する
  .side__groups
    - current_user.groups.each do |group|
      .side__group
        = link_to group_messages_path(group), class: "group" do
          .group__name
            = group.name
            .group__name__member
              %span<> (
              -# = @group.users.length
              %span<> )
          .group__message
            = group.show_last_message
  -# .side__user-lists
  -#   フレンド
  -#   = link_to "#", class: "member-add" do
  -#     = icon('fas', 'plus-square', class: 'addition')
  -# .side__users
  -#   bob
    -# = render 'users/index'

app/views/messages/index.html.haml
= render 'header'
= javascript_include_tag 'autoReload'
.wrapper
  = render 'side'
  = render 'main'

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h3 アカウントの編集
    = link_to "トップページに戻る", :back, class: 'button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "更新する", class: 'btn'

app/views/users/index.html.haml
.user-addPage
  .user-addPage__header
    %h1 友達を追加する
    = link_to "トップページに戻る", :back, class: 'button'
  %ul.user-addPage__lists
    - @users.each do |user|
      %li.user-list
        = user.name
        .add-btn{"data-user-name": user.name}
          .user-add 追加する